name: mobile_app_dev_25_26
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.10.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.12.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Apercu Pro
      fonts:
        - asset: fonts/Apercu Pro Bold Italic.otf
          weight: 700
          style: italic
        - asset: fonts/Apercu Pro Bold.otf
          weight: 700
        - asset: fonts/Apercu Pro Italic.otf
          style: italic

    - family: Apercu Pro Light
      fonts:
        - asset: fonts/Apercu Pro Light Italic.otf
          style: italic
        - asset: fonts/Apercu Pro Light.otf
        - asset: fonts/Apercu Pro Medium Italic.otf
          style: italic

    - family: Apercu Pro Medium
      fonts:
        - asset: fonts/Apercu Pro Medium.otf

    - family: Apercu Pro Regular
      fonts:
        - asset: fonts/Apercu Pro Regular.otf
